"""initial memory engine

Revision ID: d845795be795
Revises: 
Create Date: 2026-08-24 03:43:18.128715+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The Vector columns below cannot be created without this, and autogenerate
    # does not know about extensions. Kept in the first revision so a fresh
    # database is one `alembic upgrade head` away from working.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sic', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('accession', sa.String(length=32), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('fiscal_period', sa.String(length=16), nullable=True),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_format in ('html','pdf')", name=op.f('ck_documents_source_format')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_documents_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_accession'), 'documents', ['accession'], unique=True)
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index('ix_documents_company_id_filed_at', 'documents', ['company_id', 'filed_at'], unique=False)
    op.create_index(op.f('ix_documents_form_type'), 'documents', ['form_type'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalised', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_metrics_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics')),
    sa.UniqueConstraint('company_id', 'normalised', name='uq_metrics_company_id_normalised')
    )
    op.create_index(op.f('ix_metrics_company_id'), 'metrics', ['company_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.Date(), nullable=True),
    sa.Column('mention_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_topics_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('company_id', 'slug', name='uq_topics_company_id_slug')
    )
    op.create_index(op.f('ix_topics_company_id'), 'topics', ['company_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('paragraph_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('section_path', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('embedding_provider', sa.String(length=64), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks')),
    sa.UniqueConstraint('document_id', 'paragraph_id', name='uq_chunks_document_id_paragraph_id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_document_id_ordinal', 'chunks', ['document_id', 'ordinal'], unique=False)
    op.create_index('ix_chunks_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('metric_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('metric_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=True),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('is_restated', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_metric_observations_chunk_id_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_metric_observations_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], name=op.f('fk_metric_observations_metric_id_metrics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_observations')),
    sa.UniqueConstraint('metric_id', 'period', 'document_id', name='uq_metric_observations_metric_id_period_document_id')
    )
    op.create_index(op.f('ix_metric_observations_metric_id'), 'metric_observations', ['metric_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('normalised', sa.String(length=255), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_people_chunk_id_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_people_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('company_id', 'normalised', name='uq_people_company_id_normalised')
    )
    op.create_index(op.f('ix_people_company_id'), 'people', ['company_id'], unique=False)
    op.create_index(op.f('ix_people_normalised'), 'people', ['normalised'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('first_seen_at', sa.Date(), nullable=True),
    sa.Column('last_seen_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('active','dropped')", name=op.f('ck_risks_status')),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_risks_chunk_id_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_risks_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risks')),
    sa.UniqueConstraint('company_id', 'slug', name='uq_risks_company_id_slug')
    )
    op.create_index(op.f('ix_risks_company_id'), 'risks', ['company_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('chunk_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_timeline_events_chunk_id_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_timeline_events_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_timeline_events_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_timeline_events_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events')),
    sa.UniqueConstraint('company_id', 'kind', 'ref', 'occurred_at', name='uq_timeline_events_company_id_kind_ref_occurred_at')
    )
    op.create_index(op.f('ix_timeline_events_company_id'), 'timeline_events', ['company_id'], unique=False)
    op.create_index('ix_timeline_events_company_id_occurred_at', 'timeline_events', ['company_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_timeline_events_kind'), 'timeline_events', ['kind'], unique=False)
    op.create_index(op.f('ix_timeline_events_topic_id'), 'timeline_events', ['topic_id'], unique=False)
    op.create_table('topic_mentions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_topic_mentions_chunk_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_topic_mentions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_topic_mentions_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_mentions')),
    sa.UniqueConstraint('topic_id', 'chunk_id', name='uq_topic_mentions_topic_id_chunk_id')
    )
    op.create_index(op.f('ix_topic_mentions_chunk_id'), 'topic_mentions', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_topic_mentions_topic_id'), 'topic_mentions', ['topic_id'], unique=False)
    op.create_index('ix_topic_mentions_topic_id_observed_at', 'topic_mentions', ['topic_id', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # The extension is deliberately not dropped: other schemas in the same
    # database may be using it, and dropping it would take their columns with it.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topic_mentions_topic_id_observed_at', table_name='topic_mentions')
    op.drop_index(op.f('ix_topic_mentions_topic_id'), table_name='topic_mentions')
    op.drop_index(op.f('ix_topic_mentions_chunk_id'), table_name='topic_mentions')
    op.drop_table('topic_mentions')
    op.drop_index(op.f('ix_timeline_events_topic_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_kind'), table_name='timeline_events')
    op.drop_index('ix_timeline_events_company_id_occurred_at', table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_company_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_risks_company_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_people_normalised'), table_name='people')
    op.drop_index(op.f('ix_people_company_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_metric_observations_metric_id'), table_name='metric_observations')
    op.drop_table('metric_observations')
    op.drop_index('ix_chunks_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_chunks_document_id_ordinal', table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_topics_company_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_metrics_company_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_documents_form_type'), table_name='documents')
    op.drop_index('ix_documents_company_id_filed_at', table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_accession'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
