-- evident — full schema, current as of the latest migration.
--
-- Generated by concatenating db/migrations/*.sql in order; regenerate with
--     python3 tools/build_schema.py
-- Apply migrations individually to an existing database. Apply this file to a
-- fresh one.
--
-- Three layers:
--   001  substrate  — what was filed: documents, sections, paragraphs, tables
--   002  memory     — what we know: resolved entities with a time axis
--   003  cards      — what a person reads: derived projections with history

-- ===== 001_substrate.sql =================================================

-- evident-ingest — structured entities for SEC filings.
--
-- The shape here is driven by one requirement: every retrieved chunk must be
-- able to name the document, the section, the page and the paragraphs it came
-- from. So provenance columns are NOT NULL wherever the parser can guarantee
-- them, and the chunk↔paragraph link is stored explicitly rather than inferred.
--
--   psql "$DATABASE_URL" -f sql/001_schema.sql

-- Preflight: pgvector must be installed on the *server*, not just requested
-- here. Without it every table below still creates and the pipeline still runs
-- end to end — only chunk_embeddings is missing, which fails loudly at write
-- time rather than silently storing nothing.
--   macOS:  brew install pgvector
--   Debian: apt install postgresql-17-pgvector
create extension if not exists vector;

-- ---------------------------------------------------------------- companies
create table if not exists companies (
    cik         text primary key,           -- zero-padded, 10 chars
    name        text        not null,
    ticker      text,
    sic         text,
    updated_at  timestamptz not null default now()
);
create index if not exists companies_ticker_idx on companies (ticker);

-- ---------------------------------------------------------------- documents
create table if not exists documents (
    id             bigserial primary key,
    accession      text        not null unique,   -- 0000320193-25-000073
    cik            text        not null references companies (cik) on delete cascade,
    form_type      text        not null,          -- 10-K, 10-Q, 8-K, DEF 14A
    fiscal_period  text,                          -- FY2025, Q1 2026
    filed_date     date        not null,
    -- when it hit the wire, per EDGAR — never the time we fetched it
    published_at   timestamptz not null,
    source_url     text        not null,
    source_format  text        not null check (source_format in ('html', 'pdf')),
    -- lets a re-ingest detect that the bytes are unchanged and skip the work
    content_sha256 text        not null,
    page_count     int,
    ingested_at    timestamptz not null default now()
);
create index if not exists documents_cik_filed_idx on documents (cik, filed_date desc);
create index if not exists documents_form_idx      on documents (form_type, filed_date desc);

-- ----------------------------------------------------------------- sections
create table if not exists sections (
    id          bigserial primary key,
    document_id bigint not null references documents (id) on delete cascade,
    ordinal     int    not null,
    -- full path, so a citation can read "Part II › Item 7 › Capital Expenditures"
    path        text[] not null,
    title       text   not null,
    level       int    not null,
    start_page  int,
    end_page    int,
    unique (document_id, ordinal)
);
create index if not exists sections_doc_idx on sections (document_id);

-- ------------------------------------------------------------------- blocks
-- One row per paragraph. paragraph_id is deterministic and content-addressed,
-- so re-ingesting an unchanged filing produces identical ids and citations
-- issued earlier keep resolving.
create table if not exists blocks (
    id           bigserial primary key,
    document_id  bigint not null references documents (id) on delete cascade,
    section_id   bigint          references sections  (id) on delete set null,
    paragraph_id text   not null,
    ordinal      int    not null,
    page_number  int,
    text         text   not null,
    char_count   int    not null,
    unique (document_id, paragraph_id)
);
create index if not exists blocks_doc_ordinal_idx on blocks (document_id, ordinal);
create index if not exists blocks_page_idx        on blocks (document_id, page_number);

-- ----------------------------------------------------------- filing_tables
-- Tables are their own entity. Flattening a financial table into prose loses
-- the row/column relationship that makes the numbers mean anything, so cells
-- are kept intact and the table is chunked separately from the surrounding
-- narrative.
create table if not exists filing_tables (
    id          bigserial primary key,
    document_id bigint not null references documents (id) on delete cascade,
    section_id  bigint          references sections  (id) on delete set null,
    table_id    text   not null,
    ordinal     int    not null,
    page_number int,
    caption     text,
    n_rows      int    not null,
    n_cols      int    not null,
    cells       jsonb  not null,          -- [["(in millions)","2025","2024"], ...]
    unique (document_id, table_id)
);
create index if not exists filing_tables_doc_idx on filing_tables (document_id);

-- ------------------------------------------------------------------- chunks
create table if not exists chunks (
    id             bigserial primary key,
    document_id    bigint not null references documents (id) on delete cascade,
    section_id     bigint          references sections  (id) on delete set null,
    chunk_id       text   not null,
    ordinal        int    not null,
    kind           text   not null check (kind in ('prose', 'table')),
    page_start     int,
    page_end       int,
    -- the explicit link back to source paragraphs — this is what lets an
    -- answer cite "paragraph 3" rather than gesturing at a page
    paragraph_ids  text[] not null,
    table_id       text,
    text           text   not null,
    token_estimate int    not null,
    unique (document_id, chunk_id)
);
create index if not exists chunks_doc_idx on chunks (document_id, ordinal);

-- --------------------------------------------------------- chunk_embeddings
-- provider/model/dim travel with the vector so a re-embed, an A/B between
-- providers, or a migration never has to guess what produced a row.
--
-- pgvector needs a fixed dimension per column to build an index. 1536 is the
-- deploy-time default; a provider with a different dimension gets its own
-- table plus index rather than a nullable second column here.
create table if not exists chunk_embeddings (
    chunk_id   bigint      not null references chunks (id) on delete cascade,
    provider   text        not null,
    model      text        not null,
    dim        int         not null check (dim = 1536),
    embedding  vector(1536) not null,
    created_at timestamptz not null default now(),
    primary key (chunk_id, provider, model)
);
create index if not exists chunk_embeddings_ann_idx
    on chunk_embeddings using hnsw (embedding vector_cosine_ops);

-- --------------------------------------------------------------- ingest log
create table if not exists ingest_runs (
    id          bigserial primary key,
    accession   text        not null,
    stage       text        not null,
    status      text        not null check (status in ('ok', 'failed', 'skipped')),
    detail      text,
    started_at  timestamptz not null,
    finished_at timestamptz not null default now()
);
create index if not exists ingest_runs_accession_idx on ingest_runs (accession, finished_at desc);

-- ===== 002_company_memory.sql ============================================

-- evident-ingest — layer 2: company memory.
--
-- 001 stores *what was filed*: documents, sections, paragraphs, tables. That is
-- substrate. This file stores *what we know*: a durable, typed model of the
-- company that accumulates across every filing it has ever made.
--
-- The distinction matters because the two answer different questions. Layer 1
-- answers "what does page 87 say". Layer 2 answers "when did they first mention
-- Blackwell", "who has run this segment", "what did they promise in 2024 and did
-- they deliver". No amount of similarity search over layer 1 produces those —
-- they need resolved entities with a time axis.
--
-- Every row here is an assertion, and every assertion points at evidence. That
-- is the invariant the whole product rests on: nothing enters memory without a
-- paragraph that says it.

-- ------------------------------------------------------------------- memory
create table if not exists company_memory (
    company_id    bigserial primary key,
    cik           text        not null unique references companies (cik) on delete cascade,
    ticker        text,
    built_at      timestamptz,
    document_count int       not null default 0
);

-- ----------------------------------------------------------------- evidence
-- The join between substrate and memory. An entity without evidence is a
-- rumour, so every typed table below references this one.
create table if not exists evidence (
    id           bigserial primary key,
    document_id  bigint not null references documents (id) on delete cascade,
    block_id     bigint          references blocks (id) on delete cascade,
    table_id     bigint          references filing_tables (id) on delete cascade,
    paragraph_id text,
    page_number  int,
    quote        text   not null,         -- the exact span that supports the claim
    char_start   int,
    char_end     int,
    -- exactly one anchor: a paragraph or a table, never neither
    constraint evidence_has_anchor check (block_id is not null or table_id is not null)
);
create index if not exists evidence_document_idx on evidence (document_id);

-- ------------------------------------------------------------------- topics
create table if not exists topics (
    id            bigserial primary key,
    company_id    bigint not null references company_memory (company_id) on delete cascade,
    slug          text   not null,
    label         text   not null,
    first_seen_at date,
    last_seen_at  date,
    mention_count int    not null default 0,
    unique (company_id, slug)
);
create table if not exists topic_mentions (
    topic_id    bigint not null references topics   (id) on delete cascade,
    evidence_id bigint not null references evidence (id) on delete cascade,
    observed_at date   not null,
    primary key (topic_id, evidence_id)
);

-- ------------------------------------------------------------------- people
create table if not exists people (
    id            bigserial primary key,
    company_id    bigint not null references company_memory (company_id) on delete cascade,
    full_name     text   not null,
    normalised    text   not null,
    first_seen_at date,
    last_seen_at  date,
    unique (company_id, normalised)
);
-- Roles are dated because executives change jobs, and "the CFO said" means a
-- different person depending on the year.
create table if not exists person_roles (
    id          bigserial primary key,
    person_id   bigint not null references people   (id) on delete cascade,
    role        text   not null,
    from_date   date,
    to_date     date,
    evidence_id bigint          references evidence (id) on delete set null
);
create table if not exists person_statements (
    id          bigserial primary key,
    person_id   bigint not null references people   (id) on delete cascade,
    evidence_id bigint not null references evidence (id) on delete cascade,
    said_at     date   not null,
    topic_id    bigint          references topics   (id) on delete set null
);

-- ------------------------------------------------------------------ metrics
create table if not exists metrics (
    id         bigserial primary key,
    company_id bigint not null references company_memory (company_id) on delete cascade,
    name       text   not null,
    normalised text   not null,
    unit       text,
    unique (company_id, normalised)
);
-- One row per (metric, period). This is what makes a metric a series rather
-- than a number someone mentioned once.
create table if not exists metric_observations (
    id          bigserial primary key,
    metric_id   bigint  not null references metrics  (id) on delete cascade,
    document_id bigint  not null references documents (id) on delete cascade,
    evidence_id bigint  not null references evidence (id) on delete cascade,
    period      text    not null,          -- FY2025, Q1 2026
    period_end  date,
    value       numeric,
    unit        text,
    is_restated boolean not null default false,
    unique (metric_id, period, document_id)
);

-- -------------------------------------------------------------------- risks
create table if not exists risks (
    id            bigserial primary key,
    company_id    bigint not null references company_memory (company_id) on delete cascade,
    slug          text   not null,
    label         text   not null,
    category      text,
    first_seen_at date,
    last_seen_at  date,
    -- a risk that stops being disclosed is a signal, so we track disappearance
    status        text   not null default 'active'
                  check (status in ('active', 'dropped')),
    unique (company_id, slug)
);
create table if not exists risk_observations (
    id          bigserial primary key,
    risk_id     bigint not null references risks    (id) on delete cascade,
    document_id bigint not null references documents (id) on delete cascade,
    evidence_id bigint not null references evidence (id) on delete cascade,
    observed_at date   not null,
    severity    text                                -- language, not a score
);

-- ----------------------------------------------------------------- promises
-- The entity a vector database cannot represent. A forward-looking statement is
-- not a fact — it is an open obligation with a lifecycle, resolved by a later
-- filing that either delivers or quietly does not.
create table if not exists promises (
    id                  bigserial primary key,
    company_id          bigint not null references company_memory (company_id) on delete cascade,
    statement           text   not null,
    made_at             date   not null,
    made_evidence_id    bigint not null references evidence (id) on delete cascade,
    horizon             text,                       -- "H2 2025", "next fiscal year"
    due_date            date,
    topic_id            bigint          references topics (id) on delete set null,
    status              text   not null default 'open'
                        check (status in ('open', 'kept', 'broken', 'abandoned', 'unclear')),
    resolved_at         date,
    resolved_evidence_id bigint         references evidence (id) on delete set null,
    resolution_note     text,
    -- a resolved promise must say what resolved it
    constraint promise_resolution_has_evidence
        check (status = 'open' or resolved_evidence_id is not null or status = 'abandoned')
);
create index if not exists promises_open_idx on promises (company_id, status, due_date);

-- ----------------------------------------------------------------- products
create table if not exists products (
    id            bigserial primary key,
    company_id    bigint not null references company_memory (company_id) on delete cascade,
    name          text   not null,
    normalised    text   not null,
    first_seen_at date,
    last_seen_at  date,
    status        text   not null default 'mentioned'
                  check (status in ('mentioned', 'announced', 'shipping', 'discontinued')),
    unique (company_id, normalised)
);
create table if not exists product_mentions (
    product_id  bigint not null references products (id) on delete cascade,
    evidence_id bigint not null references evidence (id) on delete cascade,
    observed_at date   not null,
    primary key (product_id, evidence_id)
);

-- ------------------------------------------------------------------- events
create table if not exists events (
    id          bigserial primary key,
    company_id  bigint not null references company_memory (company_id) on delete cascade,
    kind        text   not null,           -- guidance_change, departure, acquisition, launch
    headline    text   not null,
    occurred_at date   not null,
    document_id bigint not null references documents (id) on delete cascade,
    evidence_id bigint not null references evidence (id) on delete cascade
);

-- ----------------------------------------------------------------- timeline
-- A materialised spine over everything above, so "show me this company's story"
-- is one indexed read instead of a nine-way union at query time.
create table if not exists timeline (
    id          bigserial primary key,
    company_id  bigint not null references company_memory (company_id) on delete cascade,
    occurred_at date   not null,
    kind        text   not null,           -- topic|person|metric|risk|promise|product|event|filing
    ref_table   text   not null,
    ref_id      bigint not null,
    headline    text   not null,
    topic_id    bigint          references topics   (id) on delete set null,
    evidence_id bigint          references evidence (id) on delete set null,
    unique (company_id, kind, ref_table, ref_id, occurred_at)
);
create index if not exists timeline_company_time_idx on timeline (company_id, occurred_at desc);
create index if not exists timeline_topic_idx        on timeline (topic_id, occurred_at desc);

-- ===== 003_memory_cards.sql ==============================================

-- evident-ingest — layer 3: memory cards.
--
-- Cards are what a person reads; entities are what the system stores. A card is
-- a derived projection over layer 2, never authored by hand, so rebuilding one
-- is deterministic and re-ingesting a filing cannot duplicate it.
--
-- The defining property is that a card is NOT a current value. It is an
-- append-only series of revisions, one per filing that touched it, each
-- carrying a diff against the one before. "CapEx: $14.6B" is a number; "CapEx
-- rose from $10.9B, and the increase is attributed to data-centre expansion"
-- is a card. The second is only possible because the first revision is still
-- there.

-- ------------------------------------------------------------ definitions
create table if not exists card_definitions (
    kind          text primary key,
    title         text   not null,
    description   text,
    -- which layer-2 entities feed this card
    entity_kinds  text[] not null,
    display_order int    not null default 0
);

-- --------------------------------------------------------------- routing
-- Routing rules are data, not code, so a new card ("Segment Margins ← MD&A")
-- is an insert rather than a deploy.
--
-- The six bindings bind at three different granularities, which is why this is
-- a predicate rather than a single column:
--   Revenue     -> form type      (10-Q / 10-K)
--   Products    -> document kind  (earnings call)
--   Guidance    -> speaker role   (CEO statements)
--   Risks       -> section        (Item 1A)
--   CapEx       -> section        (cash flow)
--   Litigation  -> section        (Item 3)
-- A NULL column means "don't care"; a populated one must match.
create table if not exists card_sources (
    id              bigserial primary key,
    card_kind       text   not null references card_definitions (kind) on delete cascade,
    form_types      text[],
    doc_kinds       text[],
    section_pattern text,                  -- case-insensitive regex on section title
    speaker_roles   text[],
    priority        int    not null default 0,
    -- the human-readable half of the user's table, shown as "Updates from"
    source_label    text   not null
);
create index if not exists card_sources_kind_idx on card_sources (card_kind, priority desc);

-- ----------------------------------------------------------------- cards
create table if not exists memory_cards (
    id              bigserial primary key,
    company_id      bigint not null references company_memory  (company_id) on delete cascade,
    kind            text   not null references card_definitions (kind)      on delete cascade,
    revision_count  int    not null default 0,
    first_seen_at   date,
    last_updated_at date,
    unique (company_id, kind)
);

-- ------------------------------------------------------------- revisions
-- Append-only. Nothing here is ever updated in place — an in-place update
-- would destroy the history that is the entire point of the card.
create table if not exists card_revisions (
    id                bigserial primary key,
    card_id           bigint  not null references memory_cards (id) on delete cascade,
    revision          int     not null,
    -- the filing's own date, never the time we ingested it
    as_of             date    not null,
    document_id       bigint  not null references documents (id) on delete cascade,
    source_section_id bigint           references sections  (id) on delete set null,
    source_note       text,                       -- 'FY2025 10-K · Item 7'
    summary           text,
    facts             jsonb   not null,           -- the card body at this revision
    delta             jsonb,                      -- added / removed / changed vs previous
    -- false when a filing touched the card but nothing actually moved; lets the
    -- UI show "6 updates, 2 material" instead of pretending every filing matters
    is_material       boolean not null default false,
    created_at        timestamptz not null default now(),
    unique (card_id, document_id),                -- idempotent per filing
    unique (card_id, revision)
);
create index if not exists card_revisions_card_time_idx
    on card_revisions (card_id, as_of desc);
create index if not exists card_revisions_material_idx
    on card_revisions (card_id, is_material, as_of desc);

create table if not exists card_revision_evidence (
    revision_id bigint not null references card_revisions (id) on delete cascade,
    evidence_id bigint not null references evidence       (id) on delete cascade,
    primary key (revision_id, evidence_id)
);

-- Current state is the newest revision, derived rather than stored, so it can
-- never drift out of sync with the history.
create or replace view card_current as
select distinct on (r.card_id)
       c.company_id, c.kind, r.card_id, r.id as revision_id, r.revision,
       r.as_of, r.summary, r.facts, r.delta, r.is_material, r.source_note
  from card_revisions r
  join memory_cards  c on c.id = r.card_id
 order by r.card_id, r.revision desc;

-- ------------------------------------------------------------------ seed
insert into card_definitions (kind, title, description, entity_kinds, display_order) values
    ('revenue',    'Revenue',    'Reported revenue by period, with restatements flagged.', array['metric'],            1),
    ('products',   'Products',   'Products named by management, and where each one is in its life.', array['product'],  2),
    ('guidance',   'Guidance',   'Forward-looking commitments, carried until something settles them.', array['promise'], 3),
    ('risks',      'Risks',      'Disclosed risk factors, including ones that quietly disappear.', array['risk'],        4),
    ('capex',      'CapEx',      'Capital expenditure, and what management attributes it to.', array['metric'],          5),
    ('litigation', 'Litigation', 'Legal proceedings and their movement between filings.', array['event', 'risk'],        6)
on conflict (kind) do nothing;

insert into card_sources (card_kind, form_types, doc_kinds, section_pattern, speaker_roles, source_label) values
    ('revenue',    array['10-K','10-Q'], null,                    null,                            null,              '10-Q / 10-K'),
    ('products',   null,                 array['earnings_call'],  null,                            null,              'Earnings Call'),
    ('guidance',   null,                 null,                    null,                            array['CEO'],      'CEO statements'),
    ('risks',      null,                 null,                    'item\s*1a|risk\s*factors',      null,              'Risk section'),
    ('capex',      null,                 null,                    'cash\s*flow|capital\s*expend',  null,              'Cash Flow section'),
    ('litigation', null,                 null,                    'item\s*3|legal\s*proceedings',  null,              'Legal section')
on conflict do nothing;
