#!/usr/bin/env python3
"""
Builds section 3 — the evidence demo — and splices it into index.html between
the DEMO markers. The streaming answer is generated as one span per word, each
carrying its own slice of the pinned scroll range, so "streaming" is scrubbed
by the scrollbar rather than played by a timer.

    python3 tools/demo.py
"""
import re, os

HERE = os.path.dirname(__file__)
HTML = os.path.join(HERE, '..', 'apps', 'marketing', 'index.html')

ANSWER = ("Apple increased infrastructure spending primarily to expand "
          "<em>AI compute capacity</em> across data centers and support "
          "<em>Apple Intelligence workloads</em>.")

STREAM_START, STREAM_END = 20.0, 46.0     # % of the pinned range


def stream(html):
    """One span per word, each with its own slice of the scroll range.
    <em>…</em> marks a phrase that keeps a soft glow once revealed."""
    tokens, glow = [], False
    for chunk in re.split(r'(<em>|</em>)', html):
        if chunk == '<em>':   glow = True;  continue
        if chunk == '</em>':  glow = False; continue
        for w in chunk.split():
            tokens.append((w, glow))

    span = (STREAM_END - STREAM_START) / len(tokens)
    out = []
    for i, (word, is_glow) in enumerate(tokens):
        s = STREAM_START + i * span
        e = s + span * 1.6                      # overlap so it reads continuous
        cls = 'w glow' if is_glow else 'w'
        out.append(f'<span class="{cls}" style="animation-range:contain {s:.2f}% '
                   f'contain {min(e, 100):.2f}%">{word}</span>')
    return '\n            '.join(out)


# --- the filing page ------------------------------------------------------
PARAS = [
 ("Capital expenditures for fiscal 2025 totaled $14.6 billion, compared to $10.9 "
  "billion in fiscal 2024. The increase reflects continued investment in the "
  "Company's data center footprint, manufacturing process equipment, and "
  "corporate facilities."),
 ("The Company's capital expenditure program is reviewed periodically and may be "
  "adjusted in response to changes in anticipated product demand, supply "
  "availability, and the pace of infrastructure deployment across regions."),
 ("During fiscal 2025, the Company increased payments for acquisition of property, "
  "plant and equipment, reflecting expanded investment in <mark class=\"hl\">AI compute "
  "capacity across the Company's data centers</mark> and in infrastructure supporting "
  "<mark class=\"hl hl-2\">Apple Intelligence workloads</mark>. The Company expects this "
  "level of investment to continue into fiscal 2026."),
 ("The Company believes its existing balances of cash, cash equivalents and "
  "marketable securities, along with cash generated by ongoing operations, will be "
  "sufficient to satisfy its capital expenditure requirements for at least the next "
  "12 months."),
 ("Refer to Note 4, “Property, Plant and Equipment” of the Notes to Consolidated "
  "Financial Statements for additional detail regarding the composition of the "
  "Company's long-lived asset base."),
]

ROWS = [("Data centers and related infrastructure", "6,204", "3,118"),
        ("Manufacturing process equipment",         "5,417", "5,062"),
        ("Corporate facilities and other",          "2,981", "2,742"),
        ("Total capital expenditures",              "14,602", "10,922")]


def filing():
    out = []
    out.append('<p class="pg-part">PART II</p>')
    out.append('<h4 class="pg-h">Item 7. Management&rsquo;s Discussion and Analysis of '
               'Financial Condition and Results of Operations</h4>')
    out.append('<p class="pg-sub">Capital Expenditures and Infrastructure</p>')
    for i, p in enumerate(PARAS):
        cls = 'pg-p pg-target' if i == 2 else 'pg-p'
        out.append(f'<p class="{cls}">{p}</p>')
        if i == 1:
            out.append('<table class="pg-table"><thead><tr><th>(in millions)</th>'
                       '<th>2025</th><th>2024</th></tr></thead><tbody>'
                       + ''.join(f'<tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>'
                                 for a, b, c in ROWS)
                       + '</tbody></table>')
    return '\n              '.join(out)


SECTION = f'''
<!-- ===================== 03 — THE EVIDENCE DEMO =====================
     Generated by tools/demo.py — do not hand-edit. Every step below is
     scrubbed by the scroll position, not played by a timer. -->
<section class="demo" id="evidence">
  <div class="demo-stage">
    <div class="grid-bg" aria-hidden="true">
      <svg class="grid-links" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
        <path d="M8 18 L26 34 L52 22 L74 40 L92 26" vector-effect="non-scaling-stroke"/>
        <path d="M14 62 L38 52 L58 70 L82 58" vector-effect="non-scaling-stroke"/>
        <path d="M26 34 L38 52 M74 40 L82 58 M52 22 L58 70" vector-effect="non-scaling-stroke"/>
      </svg>
    </div>

    <header class="demo-head">
      <p class="demo-eyebrow anim">03 &mdash; The proof</p>
      <h2 class="demo-h2 anim">Every answer comes with evidence.</h2>
      <p class="demo-sub anim">Stop trusting AI summaries. Elevate shows exactly where every
        answer comes from &mdash; down to the paragraph inside the filing.</p>
    </header>

    <div class="demo-panels">
      <!-- ---------- left: the conversation ---------- -->
      <div class="chat anim">
        <div class="chat-top">
          <span class="chat-dot"></span><span class="chat-name">Elevate</span>
          <span class="chat-live">Live</span>
        </div>

        <div class="bubble bubble-user anim">Why did Apple increase AI infrastructure spending in FY2025?</div>

        <div class="answer">
          <p class="stream">
            {stream(ANSWER)}<i class="caret anim" aria-hidden="true"></i>
          </p>
          <p class="answer-note anim">Spending is concentrated in data center build-out rather
            than device manufacturing, and the Company expects it to continue into fiscal 2026.</p>
        </div>

        <article class="ev anim">
          <div class="ev-top">
            <span class="ev-badge">SEC filing</span>
            <span class="ev-meta">10-K FY2025</span>
            <span class="ev-dot">&middot;</span>
            <span class="ev-meta">Page 87</span>
            <span class="ev-conf">98%</span>
          </div>
          <p class="ev-where">Source found inside Management Discussion &amp; Analysis.</p>
          <button class="ev-btn" type="button" tabindex="-1" aria-hidden="true">View evidence <span>&rarr;</span></button>
        </article>
      </div>

      <!-- ---------- right: the filing ---------- -->
      <div class="pdf anim">
        <div class="pdf-chrome">
          <span class="pdf-file">AAPL_10-K_FY2025.pdf</span>
          <span class="pdf-demo">Demo document</span>
          <span class="pdf-page-no">87 <em>/ 122</em></span>
        </div>
        <div class="pdf-viewport">
          <div class="pdf-reel">
            <div class="pdf-page pdf-page-prev" aria-hidden="true"><div class="pg-body pg-ghost"></div></div>
            <div class="pdf-page">
              <div class="pg-head"><span>Apple Inc. &middot; Form 10-K</span><span>87</span></div>
              <div class="pg-body">
              {filing()}
              </div>
            </div>
          </div>
          <aside class="cite-bubble anim">
            <p class="cb-t">10-K FY2025</p>
            <p class="cb-l">Page 87 &middot; Paragraph 3</p>
            <p class="cb-v"><span aria-hidden="true">&#10003;</span> Verified source</p>
          </aside>
        </div>
      </div>

      <svg class="connector anim" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
        <path d="M42.5 70.8 C 48.5 70.8, 46.5 51.7, 52.2 51.7" vector-effect="non-scaling-stroke"/>
      </svg>
    </div>
  </div>
</section>
'''

src = open(HTML).read()
out = re.sub(r'(<!-- DEMO:START -->\n).*?(\s*<!-- DEMO:END -->)',
             lambda m: m.group(1) + SECTION + m.group(2), src, flags=re.S)
open(HTML, 'w').write(out)
n = SECTION.count('<span class="w')
print(f'demo written: {n} streamed words, {len(PARAS)} filing paragraphs')
