#!/usr/bin/env python3
"""
Composes the parallax world markup and splices it into index.html between the
WORLD markers. Layers are ordered back-to-front; each one is taller than the
viewport and pans by (its height - 100vh) across the page scroll, so a taller
layer travels further and reads as nearer. Run:

    python3 tools/scene.py
"""
import random, re, os

random.seed(5)
HERE = os.path.dirname(__file__)
HTML = os.path.join(HERE, '..', 'apps', 'marketing', 'index.html')
S = '    '


def ridge(cls, cols, lo, hi, seed_shift=0, mode='h', quant=4):
    """A stepped pixel silhouette: one flex column per step.

    mode 'h' — column height as a %% of the band (hills, silhouettes)
    mode 'j' — column offset in px (turf, where the top edge is the horizon)
    """
    import math
    out = [f'{S}  <div class="{cls}">']
    for i in range(cols):
        t = i / cols * math.tau
        h = (math.sin(t * 2 + seed_shift) * .5 + math.sin(t * 5 + seed_shift) * .28
             + math.sin(t * 11 + seed_shift) * .12)
        h = lo + (hi - lo) * ((h + .9) / 1.8)
        step = round(h / quant) * quant              # quantise, so it reads as pixels
        var = f'--hh:{step}%' if mode == 'h' else f'--jit:{step}px'
        out.append(f'{S}    <i style="{var}"></i>')
    out.append(f'{S}  </div>')
    return out


def sp(kind, x, y, w, extra=''):
    """Free-floating sprite, positioned from the top of its layer."""
    return (f'{S}    <img class="sp" src="assets/{kind}.svg" alt="" '
            f'style="--x:{x};--y:{y};--w:{w}px{extra}">')


def stand(kind, x, w, lift=0, extra=''):
    """Sprite standing ON the ground line — anchored by its feet, so sprites of
    different heights all sit on the same horizon."""
    return (f'{S}    <img class="sp sp-b" src="assets/{kind}.svg" alt="" '
            f'style="--x:{x};--b:{lift}px;--w:{w}px{extra}">')


L = []
L.append(f'{S}<!-- generated by tools/scene.py — do not hand-edit -->')

# ---- the sky itself: four cross-faded panes, driven by scroll position ----
L.append(f'{S}<div class="sky">')
for pane in ('day', 'dusk', 'under', 'bloom'):
    L.append(f'{S}  <div class="sky-pane sky-{pane}"></div>')
L.append(f'{S}</div>')

# ---- far clouds ----------------------------------------------------------
L.append(f'{S}<div class="layer l-clouds">')
L.append(sp('sun', '82%', '9%', 128))
for i in range(16):
    kind = ('cloud-a', 'cloud-b', 'cloud-c')[i % 3]
    L.append(sp(kind, f'{random.randint(-6, 88)}%', f'{round(random.uniform(1, 62), 1)}%',
                random.choice([120, 150, 180, 210, 96])))
for i in range(5):
    L.append(sp('bird', f'{random.randint(8, 84)}%', f'{round(random.uniform(6, 40), 1)}%', 22))
L.append(f'{S}</div>')

# ---- mid hills + distant treeline ---------------------------------------
L.append(f'{S}<div class="layer l-hills">')
L.extend(ridge('hill hill-far', 34, 26, 62, 0.0))
L.append(f'{S}  <div class="standing standing-hills">')
for i in range(16):
    L.append(stand('pine' if i % 2 else 'tree', f'{random.randint(-2, 96)}%',
                   random.choice([48, 56, 64, 72]), random.randint(-6, 10)))
L.append(f'{S}  </div>')
L.extend(ridge('hill hill-near', 26, 18, 44, 1.7))
L.append(f'{S}</div>')

# ---- ground: the meadow you leave behind --------------------------------
L.append(f'{S}<div class="layer l-ground">')
L.extend(ridge('turf', 46, -18, 6, 2.4, mode='j', quant=6))
L.append(f'{S}  <div class="standing standing-ground">')
for i in range(12):
    L.append(stand('tree' if i % 3 else 'pine', f'{random.randint(-3, 94)}%',
                   random.choice([104, 126, 148, 168]), random.randint(-4, 16)))
for i in range(18):
    L.append(stand('sunflower', f'{random.randint(0, 96)}%',
                   random.choice([56, 68, 80, 94]), random.randint(-8, 6)))
for i in range(26):
    L.append(stand('grass', f'{random.randint(-2, 98)}%',
                   random.choice([56, 72, 88, 104]), random.randint(-10, 2)))
L.append(f'{S}  </div>')
L.append(f'{S}</div>')

# ---- underground: the archive you dig through ---------------------------
L.append(f'{S}<div class="layer l-under">')
for i in range(11):
    L.append(f'{S}  <div class="strata" style="--t:{5 + i * 9}%;--s:{random.randint(4,12)}px"></div>')
for i in range(70):
    L.append(f'{S}  <i class="speck" style="--x:{random.randint(0,99)}%;'
             f'--y:{round(random.uniform(2,98),1)}%;--d:{random.choice([3,4,6])}px;'
             f'--o:{round(random.uniform(.12,.34),2)}"></i>')
for i in range(36):
    L.append(sp('root', f'{random.randint(-3, 97)}%', f'{round(random.uniform(3, 96), 1)}%',
                random.choice([56, 76, 96, 120]),
                f';--r:{random.choice([0, 0, 180])}deg;--o:{round(random.uniform(.55,.95),2)}'))
for i in range(30):
    L.append(sp('doc', f'{random.randint(1, 94)}%', f'{round(random.uniform(4, 95), 1)}%',
                random.choice([56, 72, 88, 104]),
                f';--r:{random.randint(-14, 14)}deg'))
for i in range(15):
    L.append(sp('lantern', f'{random.randint(3, 93)}%', f'{round(random.uniform(6, 93), 1)}%',
                random.choice([44, 56]), ';--glow:1'))
for i in range(18):
    L.append(sp('crystal', f'{random.randint(2, 95)}%', f'{round(random.uniform(8, 94), 1)}%',
                random.choice([30, 38, 46])))
L.append(f'{S}</div>')

# ---- breaking back into the light ---------------------------------------
L.append(f'{S}<div class="layer l-bloom">')
L.extend(ridge('turf turf-bloom', 46, -22, 4, 3.1, mode='j', quant=6))
L.append(f'{S}  <div class="standing standing-bloom">')
for i in range(30):
    L.append(stand('sunflower', f'{random.randint(-2, 98)}%',
                   random.choice([64, 82, 100, 122, 140]), random.randint(-14, 10)))
for i in range(18):
    L.append(stand('grass', f'{random.randint(-2, 98)}%',
                   random.choice([64, 84, 104]), random.randint(-12, 0)))
L.append(f'{S}  </div>')
L.append(f'{S}</div>')

# ---- foreground: pixels rushing past the camera -------------------------
L.append(f'{S}<div class="layer l-fore">')
for i in range(46):
    L.append(f'{S}  <i class="streak" style="--x:{random.randint(0,99)}%;'
             f'--y:{round(random.uniform(0,99),1)}%;--h:{random.choice([6,10,14,20])}px;'
             f'--o:{round(random.uniform(.18,.5),2)}"></i>')
L.append(f'{S}</div>')

block = '\n'.join(L) + '\n'
src = open(HTML).read()
out = re.sub(r'(<!-- WORLD:START -->\n).*?(\s*<!-- WORLD:END -->)',
             lambda m: m.group(1) + block + m.group(2), src, flags=re.S)
open(HTML, 'w').write(out)
print('scene written:', block.count('<img'), 'sprites,', block.count('<div class="layer'), 'layers')
